### ISSUE TITLE
Multiple interface flaws on Windows

### ISSUE THREAD

**Issue by redmanmale** [notsecure/uTox#1000]
Every line in chat written not by me looked wrong (with some random symbol).
But my colleague (with whom I'm chatting) see my answer without first symbol.

![1](http://puu.sh/hucZ0/e96c4b3bd1.png)
![2](http://puu.sh/hud3m/ef06d8269d.png)

v. 0.2.p, Win 8.1 x64 (my), Win 7 x64 (colleague).

Also there was one very strange thing.
After I updated uTox up to 0.2.p to all my online contacts was send a request for transfer some kind of huge file (~4Gb). My colleagues haven't updated their clients yet (on that moment).
After updating that requests vanished.
What was that?

And one last shot, what function does green square button on the right side of the text field?
Because on all my windows machines (Win 7-8-8.1 (x86, x64) it doesn't work. Only bring dark veil.
Like that: ![2](http://puu.sh/hudMe/df8fee5b94.png)

**Comment by irungentoo** [comment]
Those issues were caused by some protocol breaking changes in toxcore, for that moment you didn't have the same version of toxcore as your friends which caused the issue.

That green square button is used to send a screenshot of your desktop, click on it then select the part of the screen you want to send.

**Comment by redmanmale** [comment]
@irungentoo Thanks for explanation!

**Comment by GrayHatter** [comment]
Closed for new_api break, tag me or reopen if you still have issues after your friend updates
