### ISSUE TITLE
ChromeOS Not working

### ISSUE THREAD

**Issue by ajay340** [notsecure/uTox#1020]
Downloaded it on ChromeOS and it won't launch

**Comment by GrayHatter** [comment]
ChromeOS support is experimental, expect it to break often and without warning for some time now.

It would be helpful if you could provide some more information, or does it just fail silently?

**Comment by ajayshah340** [comment]
Like when you click on the icon, its suppose to launch but it doesn't.

**Comment by GrayHatter** [comment]
no error messages?

**Comment by ajayshah340** [comment]
Nothing. 
http://i.imgur.com/9S9CsRV.png
http://i.imgur.com/w3c4IOy.png
Infact there's no launch button.

**Comment by irungentoo** [comment]
@stqism is in charge of those builds.

**Comment by ajayshah340** [comment]
May I asked @GrayHatter , why is this labeled low priority because I don't think many people can get on Tox on their chromebooks.

**Comment by GrayHatter** [comment]
Labeled as low priority because until µTox is stable on windows and linux, it'll never be stable on other platforms.  

Plus, it'd be exceeding difficult to get it working on a device I don't have access too.

**Comment by Jiufekkinity** [comment]
For me it runs stable and seems to run as it should without any crashing (apart from Antox) but really not since there are some issues that ruins the experience using utox at a chromebook:
1. The "copy" button does not work.
2. Using CTRL+C and CTR+V at the Tox IDs from a document or different program don´t do anything other than writing either "c" or "v".
3. Browsing the IDs won´t work.
4. adding contact is nearly impossible due to paste and copy/cut don´t do anything.

An updater similar to utox for windows but for Chromebook (and similar) would be great so you can be sure that this gets updated once in a while.

**Comment by GrayHatter** [comment]
https://github.com/GrayHatter/uTox/issues
