### ISSUE TITLE
[Question] How to use uTox with multiple devices? 

### ISSUE THREAD

**Issue by Jeeppler** [notsecure/uTox#1121]
How can I use uTox on multiple devices?

**Comment by LittleVulpix** [comment]
@Jeeppler, the only real way to use any tox client on multiple devices is by always copying your *.tox profile and putting in the proper directory for the client you want to move to. With this approach you can use it on multiple devices, "sort of", but be aware that you cannot use it on multiple devices simultaneously. The only other way of doing this is simply by having two different tox profiles (or however many devices you have) and have your friends add all of them... but that is pain for your friends.

GSOC was assigned to work on this issue I believe, to provide some "easier" way of being multidevice; but as of yet - due to the nature of the protocol - it is not possible.

**Comment by Jeeppler** [comment]
thanks a lot :+1:

**Comment by Sylk** [comment]
Is there any sort of update on this?

**Comment by GusL2** [comment]
I'd like to know this too. It would be very nice to have the same ID on my PC, tablet, and phone. I'm a new user of uTox, and I've suggested it as an alternative to my Yahoo IM friends.
