### ISSUE TITLE
Question about security

### ISSUE THREAD

**Issue by IndustrialOne** [notsecure/uTox#1187]
I noticed Tox doesn't use PGP, why?
Also the p2p aspect of the connection is a little vague. Can someone explain how it works in a nutshell? Are the connections relayed thru multiple peers or is it direct p2p?

**Comment by IndustrialOne** [comment]
I asked a very important question and not a single comment?

**Comment by GrayHatter** [comment]
You're asking on a dead repo mate, and that info is covered in quite a few places/websites related to tox.

**Comment by IndustrialOne** [comment]
How was I supposed to know? Does utox have an official site if it isn't here?

________________________________

**Comment by GrayHatter** [comment]
I didn't expect you to know it. I was only trying to let you know that you're posting on an issue tracker that's not really being used by anyone, so there's better places to ask. Also, because I didn't have the time to give you a full/indept response to your question, I wanted to let you know that the answer exists elsewhere. I thought you'd be able to find it from any search engine, given that you still wanted to know the answer to a question that was >1year old.
