### ISSUE TITLE
nodes are hardcoded

### ISSUE THREAD

**Issue by hasufell** [notsecure/uTox#319]
Unless I missed something... it seems that nodes are hardcoded in tox_bootstraph.h. I think this is not optimal. Nodes may change more rapidly than you can update them (and think about how long it takes to reach the end-user via distributions workflow). Also, users might want to change nodes, add nodes or select one explicitly.

That's all not possible if we just have a boostrap_nodes array during compile time.

Also see https://github.com/Jman012/Tox-DHTNodes-Updater

And commits like https://github.com/notsecure/uTox/pull/16 should be obsolete

**Comment by GrayHatter** [comment]
wontfix but I am willing to add the ability to add a node

**Comment by hasufell** [comment]
Well, that just means there is no proper "directory server" concept and nodes are completely untrustable. That's a relevant security concept though and probably no 1 attack vector.

**Comment by GrayHatter** [comment]
@hasufell not really, all you'd need is one trusted node. Else you're talking about a sybil attack, and in that case doesn't' matter how many trusted nodes you bootstrap off if there's enough nodes to overwhelm you after you connect.

**Comment by hasufell** [comment]
> not really, all you'd need is one trusted node.

Which isn't guaranteed now, because the workflow to update nodes is broken.

**Comment by GrayHatter** [comment]
No, at the very worst, it's at risk... but like I said, I'm not going to make nodes change/loadable at run time. But I would be willing to add the ability to add a node to list at run time

also wrong repo https://github.com/GrayHatter/uTox

**Comment by hasufell** [comment]
> No, at the very worst, it's at risk

That's really naive, sorry.

**Comment by GrayHatter** [comment]
explain your attack to me then... maybe I'm missing something

**Comment by hasufell** [comment]
Well, your counter-argument was "no". It seems the concept on how to verify, update and make node information as secure as possible wasn't even remotely thought through.

**Comment by GrayHatter** [comment]
@hasufell because I didn't enumerate the reasons here, in no way means I'm not aware of them, or able to reason them.

You said that a hard coded node list is the number 1 attack vector, that's an argument to be made. But you state it as a probable fact. 

Because of the way keypairs work it'd be effectively impossible to impersonate someone else. So you're not really at risk of that. So the risk of a hard coded nodelist is merely a DOS attack. Where if every bootstrap node was taken down, or taken over, the attacker would be able to block you from contacting/finding any of your contacts. That's not likely to happen. How ever if given the ability to add additional peer to connect to, you'd be able to connect to a trusted node, and get into the network.

That means that if you're able to get on to the real tox network, the only other attack, would be if there were so many attacker nodes, that they could out number the real nodes, and prevent you from contacting any real nodes. That's a sybil attack, and hardcode bootstrap on not, isn't preventable by this.

So no it's not naive, just brief because explaining secure DHT wasn't the point of this issue.
