### ISSUE TITLE
[Feature] Copy Tox ID of friend.

### ISSUE THREAD

**Issue by JasonBiggums** [notsecure/uTox#325]
Right-clicking on a friend should allow you to copy their tox ID. This would be helpful if you needed to transfer friends across different tox gui's(vemon/utox/etc)

**Comment by calimeroteknik** [comment]
@tsudoko it must be possible, since qTox does it.

**Comment by tsudoko** [comment]
@calimeroteknik as far as I know qTox' method of getting an ID will return an incorrect/incomplete one if the friend changes their nospam after being added.

**Comment by calimeroteknik** [comment]
Yeah! That's more than good enough, wouldn't you say?
The ToxID+maybe-outdated-nospam is what we have, and we want to share that with a friend.

And of course, the function we're asking for here *must* not work, and that's all good, if the nospam was changed!

**Comment by GrayHatter** [comment]
Closed as CANTFIX, perhaps we could share the name@tox.id but everything I've heard about the TOXID itself tells me this is a bad idea.

tag me if you think I've missed something...

**Comment by calimeroteknik** [comment]
@GrayHatter It does sound like a very good idea for people to be able to give the ToxID of a friend to another, only if the friend didn't change his nospam.
It's the base principle of the nospam, right? To allow friends to give your ID to friends… until this spreads too much and you change it.

Since uTox doesn't do it, I regularly fire up qTox to do it.

**Comment by muchweb** [comment]
Yes, qTox does have this function.

**Comment by Stefan-Code** [comment]
+1 This functionality would be great to have in uTox.

**Comment by GrayHatter** [comment]
move to new repo

**Comment by rwicks-cpi** [comment]
I can't find out who to contact to be able to develop the protocol.  I'm quite interested in this protocol, but I can't seem to find out who to contact in order to join up on it's development.

BTW - my tox id id:

2779E73EE1BE4E85A52DDA1E0E0DE8006905250171725CD64BE0ED1C29DACC4C03491A64CDA5

I'm JiminyIdiot.
