### ISSUE TITLE
Suggestion: Configurable notifications

### ISSUE THREAD

**Issue by reyaz006** [notsecure/uTox#344]
Tray notifications may be unwanted for someone.

As example, I'd like an option to just create and flash a minimized window, when I get a message. Or change the tray icon.

**Comment by GrayHatter** [comment]
@reyaz006 what kind of configuration options are you looking for?

**Comment by nachfuellbar** [comment]
I think he wants options to configure if a new message (or something like a contact coming online) triggers a audio notification, a flashing window etc

But i'm just guessing

**Comment by GrayHatter** [comment]
@nachfuellbar no, I get that. I want to know what options are missing? I.e. what should the notification choices be?

**Comment by GrayHatter** [comment]
closed as stale

**Comment by nachfuellbar** [comment]
I don't know which notifications @reyaz006 wanted to see
but this feature would still be good (configurable notifications for e.g. friend request, chat messages, incoming call; notifications like flashing window, tray message [i don't know how this is really called] and audio notifications)
maybe in separate tab because this could be too much for one page

**Comment by GrayHatter** [comment]
@nachfuellbar I'm planning to split up the setting page eventually, but if you'd open a new issue and describe exactly what you'd like to see that would be easier on me.
