### ISSUE TITLE
Renaming the friend

### ISSUE THREAD

**Issue by myroslav** [notsecure/uTox#610]
It would be great if uTox allowed renaming of friends (to override the name provided by remote party). If one would delete the local name for the friend, the remote name can re-appear.

The friend name is displayed in left list and on top of chat, you can let rename list name and make remote name appear in chat title either as name or as alternative name (in grey)

**Comment by codicusmaximus** [comment]
Another vote from me on that -- this seems like a critical feature otherwise people can change their names to whatever at any time and I have no idea who I am talking to.  Friends can even play dirty tricks by swapping names Bob can rename himself Sue and Sue can rename himself Bob which can lead to some nasty surprises.

**Comment by tsudoko** [comment]
Sure, I'd prefer the custom name to be in the parentheses, though.

**Comment by aaannndddyyy** [comment]
@tsudoko That might look good. "Superman (Bob)". In that case, I suggest that alphabetical ordering be done based on the locally assigned name, because, if I look for Bob in my list, I'll expect him to be displayed in the upper part, even if he calls himself now Zero. What do you think?
And what if the nicks are already long?

**Comment by tsudoko** [comment]
Well, there is a search field that could work for both custom and real names. I'm really not sure if you could do anything about names being long. I guess being able to adjust friends list width would be nice.

**Comment by myroslav** [comment]
In my case - I don't care how user names herself (in specific moment of
time), my tox client would have to behave like I want it to. In this case,
I'd want to have own way of naming contacts (with sensible default of
remote name, if I didn't provide my own). There is nothing wrong with
showing the remote name somewhere (in chat title, or in some other contact
properties box), but my nicknames are the things I'd like to see (in the
list and in chat log). And still I'm ok with having all (remote) renames of
user in my chat history, just to know how her self-perception changed over
time ;)

This brings other problem of having that custom nickname in Copy / Paste of
chat history, but that is topic of searate issue ;)

On Thu, Mar 5, 2015 at 7:43 PM, tsudoko <notifications@github.com> wrote:

> Well, there is a search field that could work for both custom and real
> names. I'm really not sure if you could do anything about names being long.
> I guess being able to adjust friends list width would be nice.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/notsecure/uTox/issues/610#issuecomment-77411531>.
>



-- 
....................................................................................................................................
Myroslav Opyr   ▪   CTO   ▪    Quintagroup   ▪   +1.917.475.4725   ▪
http://quintagroup.com
˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙˙

**Comment by GrayHatter** [comment]
closed as dup of #190
