### ISSUE TITLE
Support Avatars with Transparent Backgrounds

### ISSUE THREAD

**Issue by GrayHatter** [notsecure/uTox#729]
The simplest way to handle it would be to generate 2 .png files to use one with a white BG for when that friends chat window is active, and a light gray for when it's inactive. 

You'd also have to use the darker gray BG for the self avatar.

@Doom032 I think you're already working on this?

**Comment by Doom032** [comment]
I haven't worked on it, though I've looked into it a bit. The problem I have is I have no idea how to draw something while preserving alpha in either XRender or Win32. I guess if I knew that it wouldn't be very hard, but as I said earlier I don't have too much time to work on uTox anymore. The hints are probably in drawalpha, but I find it pretty daunting to understand on Windows and I don't immediately see how to apply it on Linux.

**Comment by tsudoko** [comment]
There's also a different background color on mouse over, so that would make 3 .png files and one for self avatar.

**Comment by Doom032** [comment]
I did some more research and found out that images don't keep their alpha channel when converting to UTOX_NATIVE_IMAGE. I also found out that we don't need to generate backgrounds, as the background color is already being drawn behind the avatars(but it's drawn over). And I found out both XRender and win32 support using image bitmasks for transparency.

I was first thinking of creating a struct UTOX_NATIVE_ALPHA_IMAGE which on xlib and win32 has 2 images(rpb_image and alpha_mask). But now I'm partial to making all UTOX_NATIVE_IMAGEs work like this, and allowing the alpha_mask image to be NULL/None if the image has no alpha.

it would mean changing a lot of code that deals with UTOX_NATIVE_IMAGEs though, as you'd have to do 'image->rgb' to get the image instead of just 'image'.

**Comment by GrayHatter** [comment]
I didn't know bitmaps could have an alpha channel. Learn something new each
day...

Is there a relevant memory usage difference between the two, if the friends
list becomes huge?

I agree with just replacing everything with alpha support. I also think we
should just rewrite the whole thing. We can hock and patch, and fix it
later, or do it the right way now...

Grep replacements shouldn't take that much time

**Comment by Doom032** [comment]
>Is there a relevant memory usage difference between the two, if the friends list becomes huge?

Well, say you have 256 friends with avatars(The max number of friends currently allowed in uTox) and all their avatars are 128x128(rather large). Without alpha their combined avatars would currently take up 256 * 24 * 128 * 128 = 100663296 bytes ~= 100.7 MiB. Alpha bitmasks would add another 256 * 8 * 128 * 128 = 33554432 bytes ~= 33.6 MiB, to make a total of ~134.2 MiB

So I don't think alpha adds much. I think the general amount is pretty high now I look at it though. We could always optimize by resizing the image to 40x40 immediately after getting it(We'd have to do this anyway if we want cubic resizing without a performance penalty). Then with 256 friends with avatars and alpha the memory usage of the avatars would always be 256 * 32 * 40 * 40 = 13107200 bytes ~= 13.1 MiB, 10 times less.

>rewrite the whole thing

What do you mean with that? I'm currently changing stuff on xlib and testing. I'll try to improve readability as I change things. What would rewriting the whole thing entail?

**Comment by GrayHatter** [comment]
> What do you mean with that? 

I mean that when you said...

> But now I'm partial to making all UTOX_NATIVE_IMAGEs work like this, and allowing the alpha image to be NULL/None if the image has no alpha.

I agree with *this* solution. If we're already adding a feature, it'd be better to just extend the existing than to add a legacy function that we'll have to kill some time later, and at that point wonder why it's still even there.

**Comment by Doom032** [comment]
>I agree with this solution. If we're already adding a feature, it'd be better to just extend the existing than to add a legacy function that we'll have to kill some time later, and at that point wonder why it's still even there.

Yeah, you're right.

Also I made a mistake in my calculations, I calculated the bits instead of the bytes, the actual resource usages would be divided by 8:
256 128x128 avatars without alpha: 12 MiB
256 128x128 avatars with alpha: 16 MiB
256 40x40 avatars with alpha: 1.5625 MiB
A lot less.

**Comment by tsudoko** [comment]
What if someone wants to receive unmodified avatars?

**Comment by Doom032** [comment]
They'll be saved to disk unmodified, but internally they'll be resized immediately loading them(instead of on each draw as is done now). I think a function like "avatarify_image(UTOX_NATIVE_IMAGE)"(maybe some other name) can be created that will resize and crop the image to fit the format needed for the avatar.

**Comment by Doom032** [comment]
Initial form of avatar transparency working on xlib:
![avatar-transparency](https://cloud.githubusercontent.com/assets/10358736/5655528/5d911348-96cf-11e4-924a-9bb755644745.png)
(See my avatar and that of my selected friend who is absolutely not me)

Seems fully functional, just need to refactor stuff to make the code better. Also need to make images get cleaned up because they're pointers to structs now. And then try to make it work on Windows.

**Comment by Doom032** [comment]
Got it working on Windows too today. Will clean up code tomorrow if I have time and then send a PR probably.

**Comment by GrayHatter** [comment]
fixed, thanks @Doom032
