### ISSUE TITLE
Tracking

### ISSUE THREAD

**Issue by concerned-user** [notsecure/uTox#775]
I don't know if this is the correct place to ask this, but I don't know what other ways to contact you and this is a very serious issue with the Tox project. irungentoo deleted these concerns from the toxcore repository, so this I have to bring it up here instead. irungentoo is enforcing censorship on this.

Recently @Proplex left the project over the following discussion: https://gist.github.com/irungentoo/5af26f5edefcdb7eac72

Soon after, I came to the following intriguing link: https://mail.tox.im/prolapse.txt

Can you explain why the Tox Foundation is tracking when Proplex visits your websites?
For an organization that says it is privacy-respecting, freedom lover and whatnot, this is highly contradictory and raise many concerns.

PS: sorry if this isn't the right repository, but this issue really needs to be discussed and it is relevant to the Tox project as a whole.

EDIT:
**Red alert:** The document of https://mail.tox.im/prolapse.txt has been edited. Really looks like someone from the Tox Foundation is trying to cover this up. Hopefully the service archive.today let us see what was previously hosted on the website.
https://archive.today/KkSWp

**Comment by concerned-user** [comment]
https://gist.github.com/urras/ba792274f5aaf662a082

**Comment by GrayHatter** [comment]
If I'm not mistaken closing issues never really deletes them, just filters them from default view. Not to mention not only does @irungentoo have access to this repo so posting here would cause him to just close this one as well. Not to mention that this really isn't an issue for µTox so I not sure what you're hoping to gain by posting this here?

Do you have something you'd like to have changed?

P.s. Having read the links you gave I personally believe that prolapse is just suffering from a little silica vaginitis. Yes toxcore is accepting donations, no they are not yet registered 501c3 tax exempt, no are they willing to publish private financial data. I don't see a problem with that personally. They've written a lot of good code for what I think is a good cause. They are well within moral high ground to ask for some donations to do whatever the f*** they want with them. Once (read: IF) they file for 501c3, then you should be asking for financial data, otherwise it's none of your damn business how they spend money they were given when there should be no specific stipulations, conditions, or limitations or donations.

Nor am I convinced by the archive link that anyone is being tracked. Http requests logs mean nothing.

**Comment by Xylemon** [comment]
This made me look into my old bookmark: https://wiki.tox.im/Not/a/gag/order.html and it seems to be gone. Does anyone know what happened to that page?

**Comment by tsudoko** [comment]
@Xylemon read what's written on the page

**Comment by irungentoo** [comment]
This discussion can be continued here: https://github.com/irungentoo/toxcore/issues/1228

@Xylemon I got rid of it because it was completely useless. I made the link you have redirect properly.

**Comment by GrayHatter** [comment]
@Xylemon ask in #tox or #tox-dev not here 

But it was deleted intentionally because it really was worthless, and doesn't provide anything but false security.

**Comment by Xylemon** [comment]
@tsudoko interesting because it didn't redirect there a minute ago...
