### ISSUE TITLE
ugly user settings german

### ISSUE THREAD

**Issue by nachfuellbar** [notsecure/uTox#904]
User settings are really ugly in german
![tox](https://cloud.githubusercontent.com/assets/5123484/6626902/86b0680c-c8fa-11e4-987c-50745dfa8a2f.PNG)

**Comment by atgote** [comment]
The same is true for the Russian localization.
![tox_gui_ru_bug](https://cloud.githubusercontent.com/assets/3784291/6825549/0922aac6-d304-11e4-9c8c-d3851f3810ea.png)

**Comment by Vort** [comment]
Copy button is also bugged
![utox_copy](https://cloud.githubusercontent.com/assets/1242858/7489556/c397b232-f3e0-11e4-885f-14bf6c94e6a9.png)

**Comment by aleloreto** [comment]
same for the "user interface" page in Spanish

![spanish](https://cloud.githubusercontent.com/assets/15605256/10874791/044465b8-8109-11e5-882d-35c45ad441a5.png)

**Comment by aleloreto** [comment]
The same for "User interface" page in Spanish

![spanish](https://cloud.githubusercontent.com/assets/15605256/10874857/9a0cac72-8109-11e5-85b1-01cfd2b9af07.png)

**Comment by GrayHatter** [comment]
let me know if this exists in the devel branch?

**Comment by Vort** [comment]
I can test this problem with russian language if you provide appropriate win64-binary.

**Comment by aleloreto** [comment]
Hello; thanks for your quick response.

I have just downloaded and installed the version for Windows that is found
at:
https://github.com/notsecure/utox-update/releases/download/latest/utox_runner.zip

This version has the same version number (version: 0.3.2), but different
texts. However, the problem persists.

Watching the Devel branch, the file
https://github.com/notsecure/uTox/blob/develop/langs/es.h
I can see that the texts for

msgid(CLOSE_TO_TRAY)
msgstr("Minimizar en la bandeja en vez de cierre")

and for

msgid(START_IN_TRAY)
msgstr("Iniciar minimizado en la bandeja del sistema")

are correct but too long.

The problem is that words in Spanish are often longer than in English, and
we use more words for the same idea. The translations provided are fine for
me, but they can't be written in this space.


So, if the space between text boxes cannot be changed, I would suggest:

msgid(CLOSE_TO_TRAY)
msgstr("Minimizar a la bandeja")

and

msgid(START_IN_TRAY)
msgstr("Iniciar en la bandeja")

**Comment by GrayHatter** [comment]
All development is at https://github.com/grayhatter/utox

**Comment by aleloreto** [comment]
Oh, sorry,

Well, in https://github.com/GrayHatter/uTox/blob/develop/langs/es.h the
keys are:

msgid(CLOSE_TO_TRAY)
msgstr("Ocultar en la bandeja al cerrar")

msgid(START_IN_TRAY)
msgstr("Ocultar en la bandeja por defecto")

Here, you can see that "Ocultar en la bandeja al cerrar" do not fit into
its given space.

And, another thing: "Ocultar en la bandeja por defecto" (literally 'Hide in
the tray by default')  is not the idea of "Start in tray", absolutely not.
Please be aware that the Spanish speaking IT world is not as mature as is
should be.

**Comment by tsudoko** [comment]
If you're able to produce a better translation, please make a pull request to [GrayHatter/uTox](https://github.com/GrayHatter/uTox)
