### ISSUE TITLE
Problem with tray tooltip status appearance

### ISSUE THREAD

**Issue by redmanmale** [notsecure/uTox#951]
In tray bubble which shows status text, after actual text shows some junk from memory.
It may be caused by some mistake in `printf` function (length of string argument).

That problem is not always appears to be, depend on lenght of status text and maybe something else.

Actual status text:
![actual status](https://puu.sh/h11oq/5993f46dd7.png)

Tray tooltip:
![tray tooltip](https://puu.sh/h11uu/22b5be4236.jpg)

v. 0.2.o, Win 8.1 x64

**Comment by tsudoko** [comment]
Are you using updater builds? This is supposed to be fixed in 8f16532, but updates are held back right now due to core API changes. All major clients need to support the new API before updates get resumed because with the new API the protocol has changed as well. Incompatibilities between clients on old and new API create problems.

**Comment by GrayHatter** [comment]
yeah, I thought I fixed this already. I'm going to version tick the master repo. 

build uTox from master and see if this still exists?

**Comment by nachfuellbar** [comment]
Seems fixed on my Client (0.2.s; Win 7 Prof)
